IF
  !See([ENEMY])
  Global("SGTAction","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("SGTVlasakSummoned","GLOBAL",0)
    Wait(2)
    DisplayStringHead(Myself,@20)
    Wait(5)
    ReallyForceSpell(Myself,CLERIC_DETECT_EVIL)
    Wait(4)
    CreateVisualEffectObject("SPFLESHS",Myself)
    Wait(1)
    DestroySelf()
END

IF
  Global("SGTAction","LOCALS",2)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,@15)
    Wait(3)
    CreateVisualEffectObject("SPSTRENH",Myself)
    Wait(1)
    DestroySelf()
END

IF
  See([ENEMY])
THEN
  RESPONSE #70
    SetGlobal("SGTAction","LOCALS",1)
    Wait(2)
    DisplayStringHead(Myself,@21)
    Wait(5)
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_HOLY_SMITE)
    Wait(4)
    DisplayStringHead(Myself,@15)
    Wait(3)
    CreateVisualEffectObject("SPSTRENH",Myself)
    Wait(1)
    DestroySelf()
  RESPONSE #30
    SetGlobal("SGTAction","LOCALS",1)
    Wait(2)
    DisplayStringHead(Myself,@22)
    Wait(5)
    ReallyForceSpell(Player1,CLERIC_PROTECTION_FROM_EVIL_10_FOOT)
    Wait(4)
    DisplayStringHead(Myself,@15)
    Wait(3)
    CreateVisualEffectObject("SPSTRENH",Myself)
    Wait(1)
    DestroySelf()
END

