IF
  !See([ENEMY])
  Global("SGTAction","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("SGTTokkarSummoned","GLOBAL",0)
    Wait(2)
    DisplayStringHead(Myself,@25)
    Wait(5)
    ReallyForceSpell(Player1,CLERIC_CHAOTIC_COMMANDS)
    Wait(4)
    CreateVisualEffectObject("SPFLESHS",Myself)
    Wait(1)
    DestroySelf()
END

IF
  Global("SGTAction","LOCALS",2)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,@15)
    Wait(3)
    CreateVisualEffectObject("SPSTRENH",Myself)
    Wait(1)
    DestroySelf()
END

IF
  See([ENEMY])
THEN
  RESPONSE #100
    SetGlobal("SGTAction","LOCALS",1)
    Wait(2)
    DisplayStringHead(Myself,@26)
    Wait(5)
    ReallyForceSpell(Player1,CLERIC_DEFENSIVE_HARMONY)
    Wait(4)
    DisplayStringHead(Myself,@15)
    Wait(3)
    CreateVisualEffectObject("SPSTRENH",Myself)
    Wait(1)
    DestroySelf()
END

