IF
  !See([ENEMY])
  Global("SGTAction","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("SGTyennSummoned","GLOBAL",0)
    Wait(2)
    DisplayStringHead(Myself,@14)
    Wait(5)
    ReallyForceSpell(Player1,CLERIC_CURE_LIGHT_WOUNDS)
    Wait(4)
    CreateVisualEffectObject("SPFLESHS",Myself)
    Wait(1)
    DestroySelf()
END

IF
  Global("SGTAction","LOCALS",2)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,@15)
    Wait(3)
    CreateVisualEffectObject("SPSTRENH",Myself)
    Wait(1)
    DestroySelf()
END

IF
  See([ENEMY])
THEN
  RESPONSE #70
    SetGlobal("SGTAction","LOCALS",1)
    Wait(2)
    DisplayStringHead(Myself,@16)
    Wait(5)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_DISINTEGRATE)
    Wait(4)
    DisplayStringHead(Myself,@15)
    Wait(3)
    CreateVisualEffectObject("SPSTRENH",Myself)
    Wait(1)
    DestroySelf()
  RESPONSE #30
    SetGlobal("SGTAction","LOCALS",1)
    Wait(2)
    DisplayStringHead(Myself,@17)
    Wait(5)
    ReallyForceSpell(Player1,WIZARD_ANIMATE_DEAD)
    Wait(4)
    DisplayStringHead(Myself,@15)
    Wait(3)
    CreateVisualEffectObject("SPSTRENH",Myself)
    Wait(1)
    DestroySelf()
END

