IF
  !See([ENEMY])
  Global("SGTAction","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("SGTCrowXSummoned","GLOBAL",0)
    Wait(2)
    DisplayStringHead(Myself,@38)
    Wait(5)
    ReallyForceSpell(Player1,CLERIC_RESIST_FIRE)
    Wait(4)
    CreateVisualEffectObject("SPFLESHS",Myself)
    Wait(1)
    DestroySelf()
END

IF
  Global("SGTAction","LOCALS",2)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,@15)
    Wait(3)
    CreateVisualEffectObject("SPSTRENH",Myself)
    Wait(1)
    DestroySelf()
END

IF
  See([ENEMY])
THEN
  RESPONSE #70
    SetGlobal("SGTAction","LOCALS",1)
    Wait(2)
    DisplayStringHead(Myself,@39)
    Wait(5)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
    Wait(4)
    DisplayStringHead(Myself,@15)
    Wait(3)
    CreateVisualEffectObject("SPSTRENH",Myself)
    Wait(1)
    DestroySelf()
  RESPONSE #30
    SetGlobal("SGTAction","LOCALS",1)
    Wait(2)
    DisplayStringHead(Myself,@40)
    Wait(5)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)
    Wait(4)
    DisplayStringHead(Myself,@15)
    Wait(3)
    CreateVisualEffectObject("SPSTRENH",Myself)
    Wait(1)
    DestroySelf()
END

