IF
  !See([ENEMY])
  Global("SGTAction","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("SGTRazfallowSummoned","GLOBAL",0)
    Wait(2)
    DisplayStringHead(Myself,@29)
    Wait(5)
    ActionOverride(Player1,ReallyForceSpell(Player1,WIZARD_VOCALIZE))
    Wait(4)
    CreateVisualEffectObject("SPFLESHS",Myself)
    Wait(1)
    DestroySelf()
END

IF
  Global("SGTAction","LOCALS",2)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,@15)
    Wait(3)
    CreateVisualEffectObject("SPSTRENH",Myself)
    Wait(1)
    DestroySelf()
END

IF
  !See([ENEMY.0.0.SORCERER])
  !See([ENEMY.0.0.MAGE_ALL])
  !See([ENEMY.0.0.BARD_ALL])
  !See([ENEMY.0.0.DRUID_ALL])
  !See([ENEMY.0.0.CLERIC_ALL])
  !See([ENEMY])
THEN
  RESPONSE #100
           Continue()
END

IF
  See(LastSeenBy(Myself))
  Allegiance(LastSeenBy(Myself),ENEMY)
  !InParty(LastSeenBy(Myself))
THEN
  RESPONSE #70
    SetGlobal("SGTAction","LOCALS",1)
    Wait(2)
    DisplayStringHead(Myself,@29)
    Wait(5)
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT)
    Wait(4)
    DisplayStringHead(Myself,@15)
    Wait(3)
    CreateVisualEffectObject("SPSTRENH",Myself)
    Wait(1)
    DestroySelf()
  RESPONSE #30
    SetGlobal("SGTAction","LOCALS",1)
    Wait(2)
    DisplayStringHead(Myself,@29)
    Wait(5)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)
    Wait(4)
    DisplayStringHead(Myself,@15)
    Wait(3)
    CreateVisualEffectObject("SPSTRENH",Myself)
    Wait(1)
    DestroySelf()
END